name: Battle
main: net.punchtree.battle.Battle
version: 0.2.1
api-version: 1.19
author: Cxom
description: Battle minigame
depend: [PunchTree-Minigames, MovementPlusPlus, PunchTree-Util]

commands:
    battle:
        usage: /battle [leave|join <game>]
        description: For the Battle minigame.